/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package richtercloud.document.scanner.gui;

import richtercloud.document.scanner.gui.conf.DocumentScannerConf;

/**
 * A dialog which allows to enforce instantiation of component values based on
 * values of a {@link DocumentScannerConf}. You have to display the dialog with
 *
 * @author richter
 */
/*
internal implementation notes:
- since the dialog is modal an needs to be closed with either the save or
discard button it's unnecessary to listen to value changes of components because
they can be retrieved when returning the new configuration instance
*/
public class DocumentScannerConfDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    private DocumentScannerConf documentScannerConf;

    /**
     * Creates new form DocumentScannerOptionsDialog
     *
     * @param parent
     * @param documentScannerConf a reference to a {@link DocumentScannerConf}
     * to be updated when values of components change
     */
    public DocumentScannerConfDialog(java.awt.Frame parent,
            DocumentScannerConf documentScannerConf) {
        super(parent,
                true //always modal
        );
        this.documentScannerConf = documentScannerConf;
        initComponents();
        this.autoGenerateIDsCheckBox.setSelected(documentScannerConf.isAutoGenerateIDs());
        this.autoSaveImageDataCheckBox.setSelected(documentScannerConf.isAutoSaveImageData());
        this.autoSaveOCRDataCheckBox.setSelected(documentScannerConf.isAutoSaveOCRData());
        this.autoOCRValueDetectionCheckBox.setSelected(documentScannerConf.isAutoOCRValueDetection());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoGenerateIDsCheckBox = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        autoSaveImageDataCheckBox = new javax.swing.JCheckBox();
        autoSaveOCRDataCheckBox = new javax.swing.JCheckBox();
        autoOCRValueDetectionCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        autoGenerateIDsCheckBox.setText("Automatically generate IDs at saving");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        discardButton.setText("Discard");
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        autoSaveImageDataCheckBox.setText("Automatically generate image data");

        autoSaveOCRDataCheckBox.setText("Automatically generate OCR data");

        autoOCRValueDetectionCheckBox.setText("Automatically detect OCR values (might be slow)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoGenerateIDsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(discardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton))
                    .addComponent(autoSaveImageDataCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoSaveOCRDataCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(autoOCRValueDetectionCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autoGenerateIDsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoSaveImageDataCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoSaveOCRDataCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoOCRValueDetectionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(discardButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.documentScannerConf.setAutoGenerateIDs(this.autoGenerateIDsCheckBox.isSelected());
        this.documentScannerConf.setAutoSaveImageData(this.autoSaveImageDataCheckBox.isSelected());
        this.documentScannerConf.setAutoSaveOCRData(this.autoSaveOCRDataCheckBox.isSelected());
        this.documentScannerConf.setAutoOCRValueDetection(this.autoOCRValueDetectionCheckBox.isSelected());
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_discardButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoGenerateIDsCheckBox;
    private javax.swing.JCheckBox autoOCRValueDetectionCheckBox;
    private javax.swing.JCheckBox autoSaveImageDataCheckBox;
    private javax.swing.JCheckBox autoSaveOCRDataCheckBox;
    private javax.swing.JButton discardButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
