/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package richtercloud.document.scanner.components;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import richtercloud.document.scanner.gui.Tools;
import richtercloud.document.scanner.ifaces.OCREngineRecognitionException;
import richtercloud.message.handler.Message;
import richtercloud.message.handler.MessageHandler;

/**
 *
 * @author richter
 */
public class OCRResultPanel extends JPanel {
    private static final long serialVersionUID = 1L;
    private final static Logger LOGGER = LoggerFactory.getLogger(OCRResultPanel.class);
    private OCRResultPanelFetcher oCRResultPanelFetcher;
    private final Set<OCRResultPanelUpdateListener> updateListeners = new HashSet<>();
    /**
     * Whether the OCR recognition process will be run in a background thread
     * (currently component is simply disabled while fetching OCR data in
     * background thread).
     */
    private boolean async = true;
    private final MessageHandler messageHandler;
    private final String initialValue;

    public OCRResultPanel(OCRResultPanelFetcher retriever,
            String initialValue,
            MessageHandler messageHandler) {
        this(retriever,
                initialValue,
                true, //async
                messageHandler);
    }

    /**
     * Creates a new {@code OCRResultPanel}.
     *
     * @param retriever
     * @param initialValue
     * @param async
     * @param messageHandler
     */
    /*
    internal implementation notes:
    - a flag to automatically start OCR recognition isn't added here for the
    same reason it's not added to ScanResultPanel
    */
    public OCRResultPanel(OCRResultPanelFetcher retriever,
            String initialValue,
            boolean async,
            MessageHandler messageHandler) {
        this.initComponents();
        this.oCRResultPanelFetcher = retriever;
        this.oCRResultTextArea.setText(initialValue);
        this.async = async;
        this.initialValue = initialValue;
        this.messageHandler = messageHandler;
        reset0();
        setValue(initialValue);
    }

    public String getValue() {
        return oCRResultTextArea.getText();
    }

    public void setValue(String oCRText) {
        this.oCRResultTextArea.setText(oCRText);
        for(OCRResultPanelUpdateListener updateListener : updateListeners) {
            updateListener.onUpdate(new OCRResultPanelUpdateEvent(oCRText));
        }
    }

    public void addUpdateListener(OCRResultPanelUpdateListener updateListener) {
        this.updateListeners.add(updateListener);
    }

    public void removeUpdateListener(OCRResultPanelUpdateListener updateListener) {
        this.updateListeners.remove(updateListener);
    }

    public boolean isAsync() {
        return async;
    }

    private void reset0() {
        if(this.initialValue != null) {
            this.oCRResultTextArea.setText(initialValue);
        }else {
            this.oCRResultTextArea.setText("");
        }
    }

    public void reset() {
        reset0();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oCRResultButton = new javax.swing.JButton();
        oCRResultTextAreaScrollPane = new javax.swing.JScrollPane();
        oCRResultTextArea = new javax.swing.JTextArea();

        oCRResultButton.setText("OCR recognition");
        oCRResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oCRResultButtonActionPerformed(evt);
            }
        });

        oCRResultTextArea.setColumns(20);
        oCRResultTextArea.setRows(5);
        oCRResultTextAreaScrollPane.setViewportView(oCRResultTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oCRResultTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(oCRResultButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oCRResultTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oCRResultButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Starts the OCR routine and sets the value on the field and the component.
     */
    /*
    internal implementation notes:
    - @TODO: implement cancelation with GUI control on a layer of the component
    */
    public void startOCR() {
        Tools.disableRecursively(this,
                false //enable
        );
        if(!async) {
            String oCRResult = startOCRNonGUI();
            startOCRGUI(oCRResult);
        }else {
            Thread oCRThread = new Thread(() -> {
                String oCRResult = startOCRNonGUI();
                SwingUtilities.invokeLater(() -> {
                    startOCRGUI(oCRResult);
                });
            },
                    "ocr-fetch-thread");
            oCRThread.start();
        }
    }

    /**
     * Fetches the OCR result from {@link oCRResultPanelFetcher} and catches
     * eventual exceptions.
     * @return the OCR result or {@code null} iff an exception occured.
     */
    private String startOCRNonGUI() {
        String oCRResult;
        try {
            oCRResult = oCRResultPanelFetcher.fetch();
            assert oCRResult != null;
        } catch (OCREngineRecognitionException ex) {
            messageHandler.handle(new Message(ex, JOptionPane.ERROR_MESSAGE));
            return null;
        }
        return oCRResult;
    }

    private void startOCRGUI(String oCRResult) {
        if(oCRResult != null) {
            //might be null if fetch has been canceled (this check is
            //unnecessary for non-async processing, but don't care
            setValue(oCRResult);
            OCRResultPanel.this.oCRResultTextArea.setCaretPosition(0);
                //scroll to top after setting value
                //from http://stackoverflow.com/questions/291115/java-swing-using-jscrollpane-and-having-it-scroll-back-to-top
                //JTextArea.scrollRectToVisible doesn't work
        }
        Tools.disableRecursively(this,
                true //enable
        );
    }

    private void oCRResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oCRResultButtonActionPerformed
        startOCR();
    }//GEN-LAST:event_oCRResultButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton oCRResultButton;
    private javax.swing.JTextArea oCRResultTextArea;
    private javax.swing.JScrollPane oCRResultTextAreaScrollPane;
    // End of variables declaration//GEN-END:variables
}
